name: Kind Runner Test
on: workflow_dispatch # Allows you to run it manually from the Actions tab

jobs:
  check-kind:
    runs-on: local-runner-set
    steps:
      - name: Who am I?
        run: |
          echo "Running on K8s node: $(hostname)"
          kubectl version --client